name: app_encuentas_prueba_tecnica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8
  flutter_bloc: ^9.1.1
  art_sweetalert: ^0.0.5
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#EEEDEB"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
